# Generated by Django 2.0.1 on 2018-01-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='content body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
