# Generated by Django 2.0.1 on 2018-01-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='file name')),
                ('file', models.FileField(upload_to='attachment', verbose_name='uploaded file')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jfu2_attachment_attachments', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterIndexTogether(
            name='attachment',
            index_together={('content_type', 'object_id')},
        ),
    ]
