# Generated by Django 2.0.1 on 2018-01-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfu2', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='attachment',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
