# Generated by Django 2.0.1 on 2018-01-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jfu2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jfu2_attachment_attachments', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='object id'),
        ),
    ]
